/* Generated By:JJTree: Do not edit this line. andOperator_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class andOperator_AST extends SimpleNode {
  equality_AST lhs;
  andOperator_AST rhs;
  String type;
  public andOperator_AST(int id) {
    super(id);
  }

  public andOperator_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitAndOperator(this, data);
  }
}
/* JavaCC - OriginalChecksum=38255a6e0517addf2c237aaa75644cab (do not edit this line) */
