/* Generated By:JJTree: Do not edit this line. arrayExpr_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class arrayExpr_AST extends SimpleNode {
  public String name;
  public int size;
  public VariableUnit variableUnit;
  public List<binaryExpression_AST> arrayIndices;
  public arrayExpr_AST(int id) {
    super(id);
  }

  public arrayExpr_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitArrayExpr(this, data);
  }
}
/* JavaCC - OriginalChecksum=e05fe8b5ea12f517052a39a0ca3e7cf5 (do not edit this line) */
