/* Generated By:JJTree: Do not edit this line. binaryExpression_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;
/***
 * Same as orExpression
 *
 */
public
class binaryExpression_AST extends SimpleNode {

  andOperator_AST lhs;
  binaryExpression_AST rhs;
  String type;
  public binaryExpression_AST(int id) {
    super(id);
  }

  public binaryExpression_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitExpression(this, data);
  }
}
/* JavaCC - OriginalChecksum=c6dcb3a965076f97bb9ba3630da89d0f (do not edit this line) */
