/* Generated By:JJTree: Do not edit this line. block_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;
import java.util.*;
public
class block_AST extends SimpleNode {

  private List<SimpleNode> statements;
  public block_AST(int id) {
    super(id);
  }

  public block_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitBlock_AST(this, data);
  }

public List<SimpleNode> getStatements() {
	return statements;
}

public void setStatements(List<SimpleNode> statements) {
	this.statements = statements;
}

public void cAccept(CodeGenerator codeGenerator, ScopeElement data, String brkLbl, String contLbl, String nextLbl) {
	codeGenerator.visitBlock(this, data, brkLbl, contLbl, nextLbl);
}
}
/* JavaCC - OriginalChecksum=d3d09de98787f3055a0a49be675822b6 (do not edit this line) */
