/* Generated By:JJTree: Do not edit this line. breakStat_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class breakStat_AST extends SimpleNode {
  public breakStat_AST(int id) {
    super(id);
  }

  public breakStat_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitBreakStat(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data,
		String brkLbl, String contLbl, String nextLbl) {
	codeGenerator.visitBreakStat(this, data, brkLbl, contLbl, nextLbl);
}
}
/* JavaCC - OriginalChecksum=b697bc099ad72ecb280ae16bae7803f0 (do not edit this line) */
