/* Generated By:JJTree: Do not edit this line. charExpr_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class charExpr_AST extends literal_AST {
  public String type = "char";
  public Character value;
  public charExpr_AST(int id) {
    super(id);
  }

  public charExpr_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitCharExpr(this, data);
  }
  
  public void cAccept(CodeGenerator codeGenerator, ScopeElement data) {
	  codeGenerator.visitCharExpr(this, data);
  }
}
/* JavaCC - OriginalChecksum=c37acfe7c3fba94c61cb8b5d2f0bb958 (do not edit this line) */
