/* Generated By:JavaCC: Do not edit this line. DecafVisitor.java Version 5.0 */
package stage2;

public interface DecafVisitor
{
  public Object visit(SimpleNode node, ScopeElement data);
  public Object visit(int_AST node, ScopeElement data);
  public Object visit(char_AST node, ScopeElement data);
  public Object visit(boolean_AST node, ScopeElement data);
  public Object visit(id_AST node, ScopeElement data);
  public Object visit(voidType_AST node, ScopeElement data);
  public Object visit(fieldExpr_AST node, ScopeElement data);
  
	Object visitStart_AST(start_AST node, ScopeElement data);
	Object visitBlock_AST(block_AST node, ScopeElement data);
	Object visitIfThenElseStat(ifThenElseStat_AST node, ScopeElement data);
	Object visitAndOperator(andOperator_AST node, ScopeElement data);
	void visitClass(ClassUnit classUnit, ScopeElement data);
	void visitMethod(MethodUnit methodUnit, ScopeElement data);
	Object visitEquality(equality_AST node, ScopeElement data);
	Object visitRelational(relational_AST node, ScopeElement data);
	Object visitSum(sum_AST node, ScopeElement data);
	Object visitFactor(factor_AST node, ScopeElement data);
	Object visitUnary(unary_AST node, ScopeElement data);
	Object visitLiteral(literal_AST node, ScopeElement data);
	Object visitExpression(binaryExpression_AST node, ScopeElement data);
	public Object visitPrimaryExisting(primaryExisting_AST node, ScopeElement data);
	public Object visitNullExpr(nullExpr_AST node, ScopeElement data);
	public Object visitBoolExpr(boolExpr_AST node, ScopeElement data);
	public Object visitIntExpr(intExpr_AST node, ScopeElement data);
	public Object visitCharExpr(charExpr_AST node, ScopeElement data);
	public Object visitStringExpr(stringExpr_AST node, ScopeElement data);
	public Object visitThisExpr(thisExpr_AST node, ScopeElement data);
	public Object visitSuperExpr(superExpr_AST node, ScopeElement data);
	public Object visitNewClassExpr(newClassExpr_AST node, ScopeElement data);
	public Object visitMethodExpr(methodExpr_AST node, ScopeElement data);
	public Object visitArrayExpr(arrayExpr_AST node, ScopeElement data);
	public Object visitIdExpr(idExpr_AST node, ScopeElement data);
	public Object visitPrimaryExisting2(primaryExisiting2_AST node, ScopeElement data);
	public Object visitNewArray(newArray_AST node, ScopeElement data);
	public Object visitWhileStat(whileStat_AST node, ScopeElement data);
	public Object visitReturnStat(returnStat_AST node, ScopeElement data);
	public Object visitExpressionStat(expressionStat_AST node, ScopeElement data);
	public Object visitMethodCall(methodCall_AST node, ScopeElement data);
	public Object visitMethodCall1(methodCall1_AST node, ScopeElement data);
	public Object visitMethodParent(methodParent_AST node, ScopeElement data);
	public Object visitMethodPrime(methodPrime_AST node, ScopeElement data);
	public Object visitMethodCall2(methodCall2_AST node, ScopeElement data);
	public Object visitAssignOperator(assignOperator_AST node, ScopeElement data);
	public Object visitFieldAccess(fieldAccess_AST node, ScopeElement data);
	public Object visitFieldAccess1(fieldAccess1_AST node, ScopeElement data);
	public Object visitVarDeclStat(varDeclStat_AST node, ScopeElement data);
	public Object visitBreakStat(breakStat_AST node, ScopeElement data);
	public Object visitContinueStat(continueStat_AST node, ScopeElement data);
	public Object visitEmptyStat(emptyStat_AST node, ScopeElement data);
}
/* JavaCC - OriginalChecksum=047d28135a64d5f568f450fd59975f2b (do not edit this line) */
