/* Generated By:JavaCC: Do not edit this line. DecafTreeConstants.java Version 5.0 */
package stage2;

public interface DecafTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART_AST = 1;
  public int JJTINT_AST = 2;
  public int JJTCHAR_AST = 3;
  public int JJTBOOLEAN_AST = 4;
  public int JJTID_AST = 5;
  public int JJTASSIGNOPERATOR_AST = 6;
  public int JJTVOIDTYPE_AST = 7;
  public int JJTBLOCK_AST = 8;
  public int JJTIFTHENELSESTAT_AST = 9;
  public int JJTWHILESTAT_AST = 10;
  public int JJTRETURNSTAT_AST = 11;
  public int JJTEXPRESSIONSTAT_AST = 12;
  public int JJTVARDECLSTAT_AST = 13;
  public int JJTBREAKSTAT_AST = 14;
  public int JJTCONTINUESTAT_AST = 15;
  public int JJTEMPTYSTAT_AST = 16;
  public int JJTNULLEXPR_AST = 17;
  public int JJTBOOLEXPR_AST = 18;
  public int JJTINTEXPR_AST = 19;
  public int JJTCHAREXPR_AST = 20;
  public int JJTSTRINGEXPR_AST = 21;
  public int JJTFIELDEXPR_AST = 22;
  public int JJTARRAYEXPR_AST = 23;
  public int JJTIDEXPR_AST = 24;
  public int JJTTHISEXPR_AST = 25;
  public int JJTSUPEREXPR_AST = 26;
  public int JJTNEWCLASSEXPR_AST = 27;
  public int JJTMETHODCALL_AST = 28;
  public int JJTMETHODCALL1_AST = 29;
  public int JJTMETHODEXPR_AST = 30;
  public int JJTMETHODCALL2_AST = 31;
  public int JJTMETHODPARENT_AST = 32;
  public int JJTMETHODPRIME_AST = 33;
  public int JJTBINARYEXPRESSION_AST = 34;
  public int JJTANDOPERATOR_AST = 35;
  public int JJTEQUALITY_AST = 36;
  public int JJTRELATIONAL_AST = 37;
  public int JJTSUM_AST = 38;
  public int JJTFACTOR_AST = 39;
  public int JJTUNARY_AST = 40;
  public int JJTPRIMARYEXISTING_AST = 41;
  public int JJTLITERAL_AST = 42;
  public int JJTPRIMARYEXISITING2_AST = 43;
  public int JJTNEWARRAY_AST = 44;


  public String[] jjtNodeName = {
    "void",
    "start_AST",
    "int_AST",
    "char_AST",
    "boolean_AST",
    "id_AST",
    "assignOperator_AST",
    "voidType_AST",
    "block_AST",
    "ifThenElseStat_AST",
    "whileStat_AST",
    "returnStat_AST",
    "expressionStat_AST",
    "varDeclStat_AST",
    "breakStat_AST",
    "continueStat_AST",
    "emptyStat_AST",
    "nullExpr_AST",
    "boolExpr_AST",
    "intExpr_AST",
    "charExpr_AST",
    "stringExpr_AST",
    "fieldExpr_AST",
    "arrayExpr_AST",
    "idExpr_AST",
    "thisExpr_AST",
    "superExpr_AST",
    "newClassExpr_AST",
    "methodCall_AST",
    "methodCall1_AST",
    "methodExpr_AST",
    "methodCall2_AST",
    "methodParent_AST",
    "methodPrime_AST",
    "binaryExpression_AST",
    "andOperator_AST",
    "equality_AST",
    "relational_AST",
    "sum_AST",
    "factor_AST",
    "unary_AST",
    "primaryExisting_AST",
    "literal_AST",
    "primaryExisiting2_AST",
    "newArray_AST",
  };
}
/* JavaCC - OriginalChecksum=c1f456f895b458975e59a67f0877a7e3 (do not edit this line) */
