/* Generated By:JJTree&JavaCC: Do not edit this line. Decaf.java */
package stage2;

import java.util.ArrayList;
import java.util.List;

public class Decaf/*@bgen(jjtree)*/implements DecafTreeConstants, DecafConstants {/*@bgen(jjtree)*/
  protected static JJTDecafState jjtree = new JJTDecafState();public static void main(String args [])
  {
    System.out.println("Reading from standard input...");
    System.out.print("Enter an expression like \u005c"1+(2+3)*var;\u005c" :");
    Decaf parser = new Decaf(System.in);
    try
    {
      List<Unit> units = parser.Start();
      for (Unit unit: units) {
        System.out.println("\u005cn");
      }
      System.out.println("Thank you.");
    }
    catch (Exception e)
    {
      System.out.println("Oops.");
      System.out.println(e.getMessage());
    }
  }

  static final public String ID() throws ParseException {
  Token t;
    t = jj_consume_token(ID);
           {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  static final public List<Unit> Start() throws ParseException {
  Unit classUnit = null;
  List<Unit> classUnitList = new ArrayList<Unit >();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      classUnit = Class();
                       classUnitList.add(classUnit);
    }
    jj_consume_token(0);
   {if (true) return classUnitList;}
    throw new Error("Missing return statement in function");
  }

  static final public Unit Class() throws ParseException {
  Unit classUnit = null;
  List<Unit> classFields = new ArrayList<Unit>();
  List<Unit> classFieldsCollection = new ArrayList<Unit>();
    jj_consume_token(CLASS);
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EXTENDS:
      jj_consume_token(EXTENDS);
      jj_consume_token(ID);
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    jj_consume_token(LCB);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PRIVATE:
      case PROTECTED:
      case PUBLIC:
      case STATIC:
      case BOOLEAN:
      case CHAR:
      case VOID:
      case INT:
      case ID:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      classFields = Member();
                            classFieldsCollection.addAll(classFields);
    }
        classUnit = new Unit();
        // Symbol table insertion to be performed
        {if (true) return classUnit;}
    jj_consume_token(RCB);
    throw new Error("Missing return statement in function");
  }

  static final public List<Unit> Member() throws ParseException {
  Unit member = null;
  List<Unit> memberList = null;
  List<Unit> allMembers = new ArrayList<Unit>();
    if (jj_2_1(2147483647)) {
      memberList = Field();
                       allMembers.addAll(memberList); {if (true) return memberList;}
    } else if (jj_2_2(2147483647)) {
      member = Method();
                    allMembers.add(member); {if (true) return memberList;}
    } else if (jj_2_3(2147483647)) {
      member = Ctor();
                  allMembers.add(member); {if (true) return memberList;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public List<Unit> Field() throws ParseException {
  FieldDetails fieldDetails = new FieldDetails();
  Modifier modifier = null;
  List<Unit> fieldList = null;
    modifier = Modifier();
                        fieldDetails.setModifier(modifier);
    fieldList = FieldDeclarations(fieldDetails);
                                              {if (true) return fieldList;}
    throw new Error("Missing return statement in function");
  }

  static final public Modifier Modifier() throws ParseException {
  Modifier modifier = new Modifier();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRIVATE:
    case PROTECTED:
    case PUBLIC:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        jj_consume_token(PUBLIC);
            modifier.setScopePublic(true);
        break;
      case PRIVATE:
        jj_consume_token(PRIVATE);
                                                      modifier.setScopePrivate(true);
        break;
      case PROTECTED:
        jj_consume_token(PROTECTED);
                                                                                                   modifier.setScopeProtected(true);
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
                                                                                                                                       {if (true) return modifier;}
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STATIC:
      jj_consume_token(STATIC);
            modifier.setScopeStatic(true);
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
                                             {if (true) return modifier;}
    throw new Error("Missing return statement in function");
  }

  static final public List<Unit> FieldDeclarations(FieldDetails fieldDetails) throws ParseException {
  SimpleNode type = null;
  List<Unit> variables = null;
    type = Type();
                fieldDetails.setType(type);
    variables = Variables(fieldDetails);
    jj_consume_token(SCOLON);
                                              {if (true) return variables;}
    throw new Error("Missing return statement in function");
  }

  static final public SimpleNode Type() throws ParseException {
  Token t = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      t = jj_consume_token(INT);
              int_AST jjtn001 = new int_AST(JJTINT_AST);
              boolean jjtc001 = true;
              jjtree.openNodeScope(jjtn001);
      try {
              jjtree.closeNodeScope(jjtn001, true);
              jjtc001 = false;
             {if (true) return jjtn001;}
      } finally {
              if (jjtc001) {
                jjtree.closeNodeScope(jjtn001, true);
              }
      }
      break;
    case CHAR:
      t = jj_consume_token(CHAR);
                char_AST jjtn002 = new char_AST(JJTCHAR_AST);
                boolean jjtc002 = true;
                jjtree.openNodeScope(jjtn002);
      try {
                jjtree.closeNodeScope(jjtn002, true);
                jjtc002 = false;
               {if (true) return jjtn002;}
      } finally {
                if (jjtc002) {
                  jjtree.closeNodeScope(jjtn002, true);
                }
      }
      break;
    case BOOLEAN:
      t = jj_consume_token(BOOLEAN);
                   boolean_AST jjtn003 = new boolean_AST(JJTBOOLEAN_AST);
                   boolean jjtc003 = true;
                   jjtree.openNodeScope(jjtn003);
      try {
                   jjtree.closeNodeScope(jjtn003, true);
                   jjtc003 = false;
                  {if (true) return jjtn003;}
      } finally {
                   if (jjtc003) {
                     jjtree.closeNodeScope(jjtn003, true);
                   }
      }
      break;
    case ID:
      t = jj_consume_token(ID);
             id_AST jjtn004 = new id_AST(JJTID_AST);
             boolean jjtc004 = true;
             jjtree.openNodeScope(jjtn004);
      try {
             jjtree.closeNodeScope(jjtn004, true);
             jjtc004 = false;
            {if (true) return jjtn004;}
      } finally {
             if (jjtc004) {
               jjtree.closeNodeScope(jjtn004, true);
             }
      }
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public List<Unit> Variables(FieldDetails fieldDetails) throws ParseException {
  List<Unit> variables = new ArrayList<Unit>();
  Unit variable = null;
    variable = Variable(fieldDetails);
                                  variables.add(variable);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      jj_consume_token(COMMA);
      variable = Variable(fieldDetails);
                                           variables.add(variable);
    }
                                                                       {if (true) return variables;}
    throw new Error("Missing return statement in function");
  }

  static final public Unit Variable(FieldDetails fieldDetails) throws ParseException {
  VariableUnit variable = new VariableUnit();
  String variableName = null;
    variableName = ID();
                      variable.setName(variableName);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LSB:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_4;
      }
      jj_consume_token(LSB);
      jj_consume_token(RSB);
                                                                  variable.setArray(true);
    }
    variable.setType(fieldDetails.getType());
    variable.setModifier(fieldDetails.getModifier());
    {if (true) return variable;}
    // Symbol table insertion

    throw new Error("Missing return statement in function");
  }

  static final public Unit Method() throws ParseException {
  MethodUnit methodUnit = new MethodUnit();
  Modifier modifier = null;
  SimpleNode type = null;
  List<Unit> formalArgs = null;
  Token t = null;
    modifier = Modifier();
                        methodUnit.setModifier(modifier);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
    case CHAR:
    case INT:
    case ID:
      type = Type();
      break;
    case VOID:
      jj_consume_token(VOID);
                               voidType_AST jjtn001 = new voidType_AST(JJTVOIDTYPE_AST);
                               boolean jjtc001 = true;
                               jjtree.openNodeScope(jjtn001);
      try {
                               jjtree.closeNodeScope(jjtn001, true);
                               jjtc001 = false;
                              type = jjtn001;
      } finally {
                               if (jjtc001) {
                                 jjtree.closeNodeScope(jjtn001, true);
                               }
      }
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                               methodUnit.setReturnType(type);
    ID();
    jj_consume_token(LP);
    formalArgs = FormalArgs();
                                        methodUnit.setFormalArgs(formalArgs);
    jj_consume_token(RP);
    Block();
   {if (true) return methodUnit;}
    throw new Error("Missing return statement in function");
  }

  static final public Unit Ctor() throws ParseException {
  MethodUnit methodUnit = new MethodUnit();
  Modifier modifier = null;
  List<Unit> formalArgs = null;
  Token t = null;
    modifier = Modifier();
                        methodUnit.setModifier(modifier);
    ID();
    jj_consume_token(LP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
    case CHAR:
    case INT:
    case ID:
      formalArgs = FormalArgs();
                                     methodUnit.setFormalArgs(formalArgs);
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    jj_consume_token(RP);
    Block();
   {if (true) return methodUnit;}
    throw new Error("Missing return statement in function");
  }

  static final public List<Unit> FormalArgs() throws ParseException {
  Unit formalArg = null;
  List<Unit> formalArgs = new ArrayList<Unit>();
    formalArg = FormalArg();
                          formalArgs.add(formalArg);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
      jj_consume_token(COMMA);
      formalArg = FormalArg();
                                   formalArgs.add(formalArg);
    }
   {if (true) return formalArgs;}
    throw new Error("Missing return statement in function");
  }

  static final public Unit FormalArg() throws ParseException {
  FieldDetails fieldDetails = new FieldDetails();
  Unit formalArg = null;
  SimpleNode type = null;
    type = Type();
                fieldDetails.setType(type);
    formalArg = Variable(fieldDetails);
                                     {if (true) return formalArg;}
    throw new Error("Missing return statement in function");
  }

  static final public void Block() throws ParseException {
                         /*@bgen(jjtree) block_AST */
  block_AST jjtn000 = new block_AST(JJTBLOCK_AST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LCB);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case BREAK:
        case CONTINUE:
        case IF:
        case NEW:
        case RETURN:
        case SUPER:
        case THIS:
        case WHILE:
        case BOOLEAN:
        case CHAR:
        case INT:
        case INTEGER:
        case TRUE:
        case FALSE:
        case CHARLITERAL:
        case STRINGLITERAL:
        case NULL:
        case LP:
        case SCOLON:
        case ID:
          ;
          break;
        default:
          jj_la1[12] = jj_gen;
          break label_6;
        }
        Statement();
      }
      jj_consume_token(RCB);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void Statement() throws ParseException {
    if (jj_2_4(3)) {
      jj_consume_token(IF);
      jj_consume_token(LP);
      Expression();
      jj_consume_token(RP);
      Statement();
                                                        ifThenElseStat_AST jjtn001 = new ifThenElseStat_AST(JJTIFTHENELSESTAT_AST);
                                                        boolean jjtc001 = true;
                                                        jjtree.openNodeScope(jjtn001);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ELSE:
          jj_consume_token(ELSE);
          Statement();
          break;
        default:
          jj_la1[13] = jj_gen;
          ;
        }
      } catch (Throwable jjte001) {
                                                        if (jjtc001) {
                                                          jjtree.clearNodeScope(jjtn001);
                                                          jjtc001 = false;
                                                        } else {
                                                          jjtree.popNode();
                                                        }
                                                        if (jjte001 instanceof RuntimeException) {
                                                          {if (true) throw (RuntimeException)jjte001;}
                                                        }
                                                        if (jjte001 instanceof ParseException) {
                                                          {if (true) throw (ParseException)jjte001;}
                                                        }
                                                        {if (true) throw (Error)jjte001;}
      } finally {
                                                        if (jjtc001) {
                                                          jjtree.closeNodeScope(jjtn001, true);
                                                        }
      }
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHILE:
        jj_consume_token(WHILE);
        jj_consume_token(LP);
        Expression();
        jj_consume_token(RP);
                                    whileStat_AST jjtn002 = new whileStat_AST(JJTWHILESTAT_AST);
                                    boolean jjtc002 = true;
                                    jjtree.openNodeScope(jjtn002);
        try {
          Statement();
        } catch (Throwable jjte002) {
                                    if (jjtc002) {
                                      jjtree.clearNodeScope(jjtn002);
                                      jjtc002 = false;
                                    } else {
                                      jjtree.popNode();
                                    }
                                    if (jjte002 instanceof RuntimeException) {
                                      {if (true) throw (RuntimeException)jjte002;}
                                    }
                                    if (jjte002 instanceof ParseException) {
                                      {if (true) throw (ParseException)jjte002;}
                                    }
                                    {if (true) throw (Error)jjte002;}
        } finally {
                                    if (jjtc002) {
                                      jjtree.closeNodeScope(jjtn002, true);
                                    }
        }
        break;
      case RETURN:
        jj_consume_token(RETURN);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 100:
          Expression();
          break;
        default:
          jj_la1[14] = jj_gen;
          ;
        }
                              returnStat_AST jjtn003 = new returnStat_AST(JJTRETURNSTAT_AST);
                              boolean jjtc003 = true;
                              jjtree.openNodeScope(jjtn003);
        try {
          jj_consume_token(SCOLON);
        } finally {
                              if (jjtc003) {
                                jjtree.closeNodeScope(jjtn003, true);
                              }
        }
        break;
      default:
        jj_la1[15] = jj_gen;
        if (jj_2_5(2)) {
          StatementExpression();
                                        expressionStat_AST jjtn004 = new expressionStat_AST(JJTEXPRESSIONSTAT_AST);
                                        boolean jjtc004 = true;
                                        jjtree.openNodeScope(jjtn004);
          try {
            jj_consume_token(SCOLON);
          } finally {
                                        if (jjtc004) {
                                          jjtree.closeNodeScope(jjtn004, true);
                                        }
          }
        } else if (jj_2_6(2)) {
                  varDeclStat_AST jjtn005 = new varDeclStat_AST(JJTVARDECLSTAT_AST);
                  boolean jjtc005 = true;
                  jjtree.openNodeScope(jjtn005);
          try {
            FieldDeclarations(new FieldDetails());
          } catch (Throwable jjte005) {
                  if (jjtc005) {
                    jjtree.clearNodeScope(jjtn005);
                    jjtc005 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte005 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte005;}
                  }
                  if (jjte005 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte005;}
                  }
                  {if (true) throw (Error)jjte005;}
          } finally {
                  if (jjtc005) {
                    jjtree.closeNodeScope(jjtn005, true);
                  }
          }
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case BREAK:
            jj_consume_token(BREAK);
             breakStat_AST jjtn006 = new breakStat_AST(JJTBREAKSTAT_AST);
             boolean jjtc006 = true;
             jjtree.openNodeScope(jjtn006);
            try {
              jj_consume_token(SCOLON);
            } finally {
             if (jjtc006) {
               jjtree.closeNodeScope(jjtn006, true);
             }
            }
            break;
          case CONTINUE:
            jj_consume_token(CONTINUE);
                continueStat_AST jjtn007 = new continueStat_AST(JJTCONTINUESTAT_AST);
                boolean jjtc007 = true;
                jjtree.openNodeScope(jjtn007);
            try {
              jj_consume_token(SCOLON);
            } finally {
                if (jjtc007) {
                  jjtree.closeNodeScope(jjtn007, true);
                }
            }
            break;
          case SCOLON:
     emptyStat_AST jjtn008 = new emptyStat_AST(JJTEMPTYSTAT_AST);
     boolean jjtc008 = true;
     jjtree.openNodeScope(jjtn008);
            try {
              jj_consume_token(SCOLON);
            } finally {
     if (jjtc008) {
       jjtree.closeNodeScope(jjtn008, true);
     }
            }
            break;
          default:
            jj_la1[16] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    }
  }

  static final public void Literal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
    nullExpr_AST jjtn001 = new nullExpr_AST(JJTNULLEXPR_AST);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(NULL);
      } finally {
    if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, true);
    }
      }
      break;
    case TRUE:
     boolExpr_AST jjtn002 = new boolExpr_AST(JJTBOOLEXPR_AST);
     boolean jjtc002 = true;
     jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(TRUE);
      } finally {
     if (jjtc002) {
       jjtree.closeNodeScope(jjtn002, true);
     }
      }
      break;
    case FALSE:
     boolExpr_AST jjtn003 = new boolExpr_AST(JJTBOOLEXPR_AST);
     boolean jjtc003 = true;
     jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(FALSE);
      } finally {
     if (jjtc003) {
       jjtree.closeNodeScope(jjtn003, true);
     }
      }
      break;
    case INTEGER:
     intExpr_AST jjtn004 = new intExpr_AST(JJTINTEXPR_AST);
     boolean jjtc004 = true;
     jjtree.openNodeScope(jjtn004);
      try {
        jj_consume_token(INTEGER);
      } finally {
     if (jjtc004) {
       jjtree.closeNodeScope(jjtn004, true);
     }
      }
      break;
    case CHARLITERAL:
     charExpr_AST jjtn005 = new charExpr_AST(JJTCHAREXPR_AST);
     boolean jjtc005 = true;
     jjtree.openNodeScope(jjtn005);
      try {
        jj_consume_token(CHARLITERAL);
      } finally {
     if (jjtc005) {
       jjtree.closeNodeScope(jjtn005, true);
     }
      }
      break;
    case STRINGLITERAL:
     stringExpr_AST jjtn006 = new stringExpr_AST(JJTSTRINGEXPR_AST);
     boolean jjtc006 = true;
     jjtree.openNodeScope(jjtn006);
      try {
        jj_consume_token(STRINGLITERAL);
      } finally {
     if (jjtc006) {
       jjtree.closeNodeScope(jjtn006, true);
     }
      }
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void StatementExpression() throws ParseException {
    MethodCall();
  }

  static final public void MethodCall() throws ParseException {
                                   /*@bgen(jjtree) methodCall_AST */
  methodCall_AST jjtn000 = new methodCall_AST(JJTMETHODCALL_AST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      MethodCall_1();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
        MethodCall_2();
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void MethodCall_1() throws ParseException {
                                     /*@bgen(jjtree) methodCall_AST */
  methodCall_AST jjtn000 = new methodCall_AST(JJTMETHODCALL_AST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      MethodParent();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
        MethodPrime();
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[20] = jj_gen;
        ;
      }
      jj_consume_token(RP);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void MethodCall_2() throws ParseException {
    if (jj_2_7(2147483647)) {
      jj_consume_token(DOT);
      jj_consume_token(ID);
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[21] = jj_gen;
        ;
      }
                                                                                                            AstMethodExpr jjtn001 = new AstMethodExpr(JJTASTMETHODEXPR);
                                                                                                            boolean jjtc001 = true;
                                                                                                            jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(RP);
      } finally {
                                                                                                            if (jjtc001) {
                                                                                                              jjtree.closeNodeScope(jjtn001, true);
                                                                                                            }
      }
      MethodCall_2();
    } else if (jj_2_8(2147483647)) {
      jj_consume_token(DOT);
      jj_consume_token(ID);
      jj_consume_token(LSB);
      Expression();
      jj_consume_token(RSB);
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
      jj_consume_token(RP);
      MethodCall_2();
    } else if (jj_2_9(2147483647)) {
      jj_consume_token(DOT);
      jj_consume_token(ID);
      MethodPrime();
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[23] = jj_gen;
        ;
      }
      jj_consume_token(RP);
      MethodCall_2();
    } else if (jj_2_10(2147483647)) {
      jj_consume_token(DOT);
      jj_consume_token(ID);
      jj_consume_token(LSB);
      Expression();
      jj_consume_token(RSB);
      MethodPrime();
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[24] = jj_gen;
        ;
      }
      jj_consume_token(RP);
      MethodCall_2();
    } else if (jj_2_11(2147483647)) {
      jj_consume_token(DOT);
      jj_consume_token(ID);
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[25] = jj_gen;
        ;
      }
      jj_consume_token(RP);
    } else if (jj_2_12(2147483647)) {
      jj_consume_token(DOT);
      jj_consume_token(ID);
      jj_consume_token(LSB);
      Expression();
      jj_consume_token(RSB);
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[26] = jj_gen;
        ;
      }
      jj_consume_token(RP);
    } else if (jj_2_13(2147483647)) {
      jj_consume_token(DOT);
      jj_consume_token(ID);
      MethodPrime();
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[27] = jj_gen;
        ;
      }
      jj_consume_token(RP);
    } else if (jj_2_14(2147483647)) {
      jj_consume_token(DOT);
      jj_consume_token(ID);
      jj_consume_token(LSB);
      Expression();
      jj_consume_token(RSB);
      MethodPrime();
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[28] = jj_gen;
        ;
      }
      jj_consume_token(RP);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void MethodParent() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NEW:
    case SUPER:
    case THIS:
    case INTEGER:
    case TRUE:
    case FALSE:
    case CHARLITERAL:
    case STRINGLITERAL:
    case NULL:
    case LP:
      PrimaryMethodParent();
      jj_consume_token(DOT);
                                 fieldExpr_AST jjtn001 = new fieldExpr_AST(JJTFIELDEXPR_AST);
                                 boolean jjtc001 = true;
                                 jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(ID);
      } finally {
                                 if (jjtc001) {
                                   jjtree.closeNodeScope(jjtn001, true);
                                 }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LSB:
        jj_consume_token(LSB);
        Expression();
                                                                           arrayExpr_AST jjtn002 = new arrayExpr_AST(JJTARRAYEXPR_AST);
                                                                           boolean jjtc002 = true;
                                                                           jjtree.openNodeScope(jjtn002);
        try {
          jj_consume_token(RSB);
        } finally {
                                                                           if (jjtc002) {
                                                                             jjtree.closeNodeScope(jjtn002, true);
                                                                           }
        }
        break;
      default:
        jj_la1[29] = jj_gen;
        ;
      }
      break;
    case ID:
       idExpr_AST jjtn003 = new idExpr_AST(JJTIDEXPR_AST);
       boolean jjtc003 = true;
       jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(ID);
      } finally {
       if (jjtc003) {
         jjtree.closeNodeScope(jjtn003, true);
       }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LSB:
        jj_consume_token(LSB);
        Expression();
                                             arrayExpr_AST jjtn004 = new arrayExpr_AST(JJTARRAYEXPR_AST);
                                             boolean jjtc004 = true;
                                             jjtree.openNodeScope(jjtn004);
        try {
          jj_consume_token(RSB);
        } finally {
                                             if (jjtc004) {
                                               jjtree.closeNodeScope(jjtn004, true);
                                             }
        }
        break;
      default:
        jj_la1[30] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void PrimaryMethodParent() throws ParseException {
    if (jj_2_15(3)) {
      Literal();
    } else if (jj_2_16(3)) {
      thisExpr_AST jjtn001 = new thisExpr_AST(JJTTHISEXPR_AST);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(THIS);
      } finally {
      if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, true);
      }
      }
    } else if (jj_2_17(3)) {
      superExpr_AST jjtn002 = new superExpr_AST(JJTSUPEREXPR_AST);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(SUPER);
      } finally {
      if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, true);
      }
      }
    } else if (jj_2_18(3)) {
      jj_consume_token(LP);
      Expression();
      jj_consume_token(RP);
    } else if (jj_2_19(3)) {
      jj_consume_token(NEW);
      jj_consume_token(ID);
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 100:
        ActualArguments();
        break;
      default:
        jj_la1[32] = jj_gen;
        ;
      }
                                           methodExpr_AST jjtn003 = new methodExpr_AST(JJTMETHODEXPR_AST);
                                           boolean jjtc003 = true;
                                           jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(RP);
      } finally {
                                           if (jjtc003) {
                                             jjtree.closeNodeScope(jjtn003, true);
                                           }
      }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void MethodPrime() throws ParseException {
    if (jj_2_20(2147483647)) {
      jj_consume_token(DOT);
            fieldExpr_AST jjtn001 = new fieldExpr_AST(JJTFIELDEXPR_AST);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(ID);
      } finally {
            if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
      }
      MethodPrime();
    } else if (jj_2_21(2147483647)) {
      jj_consume_token(DOT);
            fieldExpr_AST jjtn002 = new fieldExpr_AST(JJTFIELDEXPR_AST);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(ID);
      } finally {
            if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
      }
      jj_consume_token(LSB);
      Expression();
                                                   arrayExpr_AST jjtn003 = new arrayExpr_AST(JJTARRAYEXPR_AST);
                                                   boolean jjtc003 = true;
                                                   jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(RSB);
      } finally {
                                                   if (jjtc003) {
                                                     jjtree.closeNodeScope(jjtn003, true);
                                                   }
      }
      MethodPrime();
    } else if (jj_2_22(3)) {
      jj_consume_token(DOT);
                         fieldExpr_AST jjtn004 = new fieldExpr_AST(JJTFIELDEXPR_AST);
                         boolean jjtc004 = true;
                         jjtree.openNodeScope(jjtn004);
      try {
        jj_consume_token(ID);
      } finally {
                         if (jjtc004) {
                           jjtree.closeNodeScope(jjtn004, true);
                         }
      }
      jj_consume_token(LSB);
      Expression();
                                                                arrayExpr_AST jjtn005 = new arrayExpr_AST(JJTARRAYEXPR_AST);
                                                                boolean jjtc005 = true;
                                                                jjtree.openNodeScope(jjtn005);
      try {
        jj_consume_token(RSB);
      } finally {
                                                                if (jjtc005) {
                                                                  jjtree.closeNodeScope(jjtn005, true);
                                                                }
      }
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
        jj_consume_token(DOT);
            fieldExpr_AST jjtn006 = new fieldExpr_AST(JJTFIELDEXPR_AST);
            boolean jjtc006 = true;
            jjtree.openNodeScope(jjtn006);
        try {
          jj_consume_token(ID);
        } finally {
            if (jjtc006) {
              jjtree.closeNodeScope(jjtn006, true);
            }
        }
        break;
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void ActualArguments() throws ParseException {
    Expression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      Expression();
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
  }

  static final public void Expression() throws ParseException {
    jj_consume_token(100);
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_3R_56() {
    if (jj_3R_76()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_77()) jj_scanpos = xsp;
    if (jj_scan_token(LP)) return true;
    xsp = jj_scanpos;
    if (jj_3R_90()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_3R_56()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_89()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_10() {
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_scan_token(STRINGLITERAL)) return true;
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_scan_token(CHARLITERAL)) return true;
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  static private boolean jj_3R_83() {
    if (jj_scan_token(SCOLON)) return true;
    return false;
  }

  static private boolean jj_3R_82() {
    if (jj_scan_token(CONTINUE)) return true;
    if (jj_scan_token(SCOLON)) return true;
    return false;
  }

  static private boolean jj_3R_81() {
    if (jj_scan_token(BREAK)) return true;
    if (jj_scan_token(SCOLON)) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_3R_10()) return true;
    if (jj_scan_token(SCOLON)) return true;
    return false;
  }

  static private boolean jj_3R_80() {
    if (jj_scan_token(RETURN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(100)) jj_scanpos = xsp;
    if (jj_scan_token(SCOLON)) return true;
    return false;
  }

  static private boolean jj_3R_79() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LP)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_75()) return true;
    return false;
  }

  static private boolean jj_3R_75() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) {
    jj_scanpos = xsp;
    if (jj_3R_82()) {
    jj_scanpos = xsp;
    if (jj_3R_83()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_3R_75()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LP)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_75()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_86()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_scan_token(LCB)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_55()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RCB)) return true;
    return false;
  }

  static private boolean jj_3R_53() {
    if (jj_3R_31()) return true;
    if (jj_3R_61()) return true;
    return false;
  }

  static private boolean jj_3R_78() {
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(RSB)) return true;
    return false;
  }

  static private boolean jj_3R_73() {
    if (jj_scan_token(PROTECTED)) return true;
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_3R_53()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_54()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_scan_token(VOID)) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    if (jj_3R_23()) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_3R_31()) return true;
    return false;
  }

  static private boolean jj_3R_8() {
    if (jj_3R_23()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    if (jj_3R_26()) return true;
    if (jj_scan_token(LP)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_72() {
    if (jj_scan_token(PRIVATE)) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_61() {
    if (jj_3R_26()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_78()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_74() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_61()) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    if (jj_3R_61()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_74()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_70() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_91() {
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_scan_token(CHAR)) return true;
    return false;
  }

  static private boolean jj_3R_66() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_62() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_scan_token(100)) return true;
    return false;
  }

  static private boolean jj_3R_57() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    if (jj_3R_31()) return true;
    if (jj_3R_32()) return true;
    if (jj_scan_token(SCOLON)) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_92() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_68() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3_21() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3_20() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_scan_token(100)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_62()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_52() {
    if (jj_scan_token(STATIC)) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_71() {
    if (jj_scan_token(PUBLIC)) return true;
    return false;
  }

  static private boolean jj_3R_64() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3_22() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    return false;
  }

  static private boolean jj_3R_69() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_52()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_88() {
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_42() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_65() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_7() {
    if (jj_3R_23()) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3_19() {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_92()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3_18() {
    if (jj_scan_token(LP)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3R_90() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3_17() {
    if (jj_scan_token(SUPER)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_7()) return true;
    return false;
  }

  static private boolean jj_3_16() {
    if (jj_scan_token(THIS)) return true;
    return false;
  }

  static private boolean jj_3R_67() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_87() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) {
    jj_scanpos = xsp;
    if (jj_3_19()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_15() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_20()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3R_85() {
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_88()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_19()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3R_84() {
    if (jj_3R_87()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_91()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_76() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_84()) {
    jj_scanpos = xsp;
    if (jj_3R_85()) return true;
    }
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_18()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_17()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_70()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_14()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_40() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_69()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3R_86() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_75()) return true;
    return false;
  }

  static private boolean jj_3R_77() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_68()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_12()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_67()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_66()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_89() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LSB)) return true;
    if (jj_scan_token(100)) return true;
    if (jj_scan_token(RSB)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_64()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_63()) jj_scanpos = xsp;
    if (jj_scan_token(RP)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public DecafTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[35];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x400,0x2000,0xf170000,0x70000,0x70000,0x100000,0xb000000,0x0,0x0,0xf000000,0xb000000,0x0,0xbe8ca00,0x1000,0x0,0x880000,0xa00,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x608000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4000,0x800,0x0,0x0,0x4000,0x20fe,0x0,0x0,0x0,0x2000,0x7e,0x8000,0x8000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x800,0x800,0xfe,0x0,0x8000,0x4000,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x2,0x0,0x0,0x0,0x2,0x0,0x0,0x2,0x2,0x0,0x2,0x0,0x10,0x0,0x0,0x0,0x0,0x0,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x0,0x0,0x2,0x10,0x0,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[22];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Decaf(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Decaf(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new DecafTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Decaf(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new DecafTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Decaf(DecafTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(DecafTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[101];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 35; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 101; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 22; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
