/* Generated By:JJTree: Do not edit this line. equality_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class equality_AST extends SimpleNode {
  relational_AST lhs;
  Token sign;
  equality_AST rhs;
  String type;
  public equality_AST(int id) {
    super(id);
  }

  public equality_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitEquality(this, data);
  }
}
/* JavaCC - OriginalChecksum=7427cfae9abeaca294bb9cf7cba87f3a (do not edit this line) */
