/* Generated By:JJTree: Do not edit this line. fieldAccess_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class fieldAccess_AST extends SimpleNode {
	fieldAccess1_AST fAccess1;
	methodPrime_AST mPrime;
  public fieldAccess_AST(int id) {
    super(id);
  }

  public fieldAccess_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitFieldAccess(this, data);
  }
}
/* JavaCC - OriginalChecksum=1d0382739c17f7f3f2bc12f7dde5b523 (do not edit this line) */
