/* Generated By:JJTree: Do not edit this line. id_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class id_AST extends SimpleNode {
  private Unit unit;
  
  
  public id_AST(int id) {
    super(id);
  }

  public id_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visit(this, data);
  }

  public Unit getUnit() {
	return unit;
  }

  public void setUnit(Unit unit) {
	this.unit = unit;
  }
}
/* JavaCC - OriginalChecksum=f1da71f7e2a65f35751569021325d70f (do not edit this line) */
