/* Generated By:JJTree: Do not edit this line. ifThenElseStat_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class ifThenElseStat_AST extends SimpleNode {
  SimpleNode ifStat, elseStat;
  binaryExpression_AST condition;
  
  public ifThenElseStat_AST(int id) {
    super(id);
  }

  public ifThenElseStat_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitIfThenElseStat(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data, String brkLbl, String contLbl, String nextLbl) {
	codeGenerator.visitIfThenElseStat(this, data, brkLbl, contLbl, nextLbl);
	
}
}
/* JavaCC - OriginalChecksum=09b486170d6899b1ce665c48eadba959 (do not edit this line) */
