/* Generated By:JJTree: Do not edit this line. lesserEqualOperator_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class lesserEqualOperator_AST extends SimpleNode {
  public lesserEqualOperator_AST(int id) {
    super(id);
  }

  public lesserEqualOperator_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=96224ad0bce486d424e44802b3ace510 (do not edit this line) */
