/* Generated By:JJTree: Do not edit this line. literal_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class literal_AST extends SimpleNode {
  public literal_AST(int id) {
    super(id);
  }

  public literal_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitLiteral(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data) {
	codeGenerator.visitLiteral(this, data);
}
}
/* JavaCC - OriginalChecksum=cc916afe2d893d4fb9bc855a7d26887f (do not edit this line) */
