/* Generated By:JJTree: Do not edit this line. methodParent_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class methodParent_AST extends SimpleNode {
  SimpleNode primaryMethodParent;
  String name;
  binaryExpression_AST arrayIndex;
  boolean isMethod = false;
  List<binaryExpression_AST> actualArgs;
  public methodParent_AST(int id) {
    super(id);
  }

  public methodParent_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitMethodParent(this, data);
  }
}
/* JavaCC - OriginalChecksum=5485377571bad95d0a25a87881604779 (do not edit this line) */
