/* Generated By:JJTree: Do not edit this line. methodExpr_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class methodExpr_AST extends SimpleNode {
  public String name;
  public List<binaryExpression_AST> arguments;
  public MethodUnit methodUnit;
  public methodExpr_AST(int id) {
    super(id);
  }

  public methodExpr_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitMethodExpr(this, data);
  }
}
/* JavaCC - OriginalChecksum=32ebe66d90e33fd3845b63176d21b4be (do not edit this line) */
