/* Generated By:JJTree: Do not edit this line. methodCall1_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class methodCall1_AST extends SimpleNode {
  methodParent_AST mParent;
  methodPrime_AST mPrime;
  List<binaryExpression_AST> actualArgs;
  public methodCall1_AST(int id) {
    super(id);
  }

  public methodCall1_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitMethodCall1(this, data);
  }
}
/* JavaCC - OriginalChecksum=1caff3e3a1131d8eb7ef884f48ea9ad2 (do not edit this line) */
