/* Generated By:JJTree: Do not edit this line. methodCall2_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class methodCall2_AST extends SimpleNode {
  String name;
  List<binaryExpression_AST> actualArgs;
  methodCall2_AST m2;
  binaryExpression_AST arrayIndex;
  methodPrime_AST mPrime;
  ScopeElement callerScope;
  public methodCall2_AST(int id) {
    super(id);
  }

  public methodCall2_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitMethodCall2(this, data);
  }
}
/* JavaCC - OriginalChecksum=5c86295ee4299a33daf99b1078b14f2f (do not edit this line) */
