/* Generated By:JJTree: Do not edit this line. newClassExpr_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class newClassExpr_AST extends SimpleNode {
  public String name;
  public List<binaryExpression_AST> arguments;
  public ClassUnit classUnit;
  public newClassExpr_AST(int id) {
    super(id);
  }

  public newClassExpr_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. 
 * @throws ParseException **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data){
    return visitor.visitNewClassExpr(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2878a2bf63cf5df9bf92742d446a903 (do not edit this line) */
