/* Generated By:JJTree: Do not edit this line. primaryExisiting2_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class primaryExisiting2_AST extends SimpleNode {
  String attribute;
  List<binaryExpression_AST> arguments = null;
  binaryExpression_AST arrayExpression = null;
  primaryExisiting2_AST p2;
  ScopeElement callerScope;
  
  
  public primaryExisiting2_AST(int id) {
    super(id);
  }

  public primaryExisiting2_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitPrimaryExisting2(this, data);
  }
}
/* JavaCC - OriginalChecksum=750a289a92f173d4938e9ff01b2cbfdd (do not edit this line) */
