/* Generated By:JJTree: Do not edit this line. primaryExisting_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class primaryExisting_AST extends SimpleNode {
  SimpleNode p1 ;
  primaryExisiting2_AST p2 ;
  public primaryExisting_AST(int id) {
    super(id);
  }

  public primaryExisting_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitPrimaryExisting(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data) {
	codeGenerator.visitPrimary(this, data);
}
}
/* JavaCC - OriginalChecksum=007e0f262e1ca4d56fffc2f171deae34 (do not edit this line) */
