/* Generated By:JJTree: Do not edit this line. relational_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class relational_AST extends SimpleNode {
  relational_AST rhs;
  Token sign;
  sum_AST lhs;
  String type;
  public relational_AST(int id) {
    super(id);
  }

  public relational_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitRelational(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data,
		String falsLab) {
	codeGenerator.visitRelational(this, data, falsLab);
}
}
/* JavaCC - OriginalChecksum=20e79bc8eef49187462588f7dc7c6fb0 (do not edit this line) */
