/* Generated By:JJTree: Do not edit this line. returnStat_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class returnStat_AST extends SimpleNode {
  binaryExpression_AST expr;
  public returnStat_AST(int id) {
    super(id);
  }

  public returnStat_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitReturnStat(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data,
		String brkLbl, String contLbl, String nextLbl) {
	codeGenerator.visitReturnStat(this, data, brkLbl, contLbl, nextLbl);
}
}
/* JavaCC - OriginalChecksum=21a491b147986e9e90ef07c282a462d4 (do not edit this line) */
