/* Generated By:JJTree: Do not edit this line. start_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class start_AST extends SimpleNode {
  private List<Unit> classes;
  public start_AST(int id) {
    super(id);
  }

  public start_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visit(this, data);
  }

/**
 * @return the classes
 */
public List<Unit> getClasses() {
	return classes;
}

/**
 * @param classes the classes to set
 */
public void setClasses(List<Unit> classes) {
	this.classes = classes;
}
}
/* JavaCC - OriginalChecksum=fd63257a31d4d2f342d8e94bdaf067a8 (do not edit this line) */
