/* Generated By:JJTree: Do not edit this line. superExpr_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class superExpr_AST extends SimpleNode {
  public superExpr_AST(int id) {
    super(id);
  }

  public superExpr_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitSuperExpr(this, data);
  }
}
/* JavaCC - OriginalChecksum=3fe2883373739578130ef4b65b6bf61a (do not edit this line) */
