/* Generated By:JJTree: Do not edit this line. thisExpr_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class thisExpr_AST extends SimpleNode {
  public thisExpr_AST(int id) {
    super(id);
  }

  public thisExpr_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitThisExpr(this, data);
  }
}
/* JavaCC - OriginalChecksum=38b48b11457fe240525df291e370d94e (do not edit this line) */
