/* Generated By:JJTree: Do not edit this line. unary_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class unary_AST extends SimpleNode {
  Token sign;
  binaryExpression_AST expr;
  String type;
  SimpleNode primary;
  public unary_AST(int id) {
    super(id);
  }

  public unary_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitUnary(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data,
		String falsLbl) {
	codeGenerator.visitUnary(this,data, falsLbl);
}
}
/* JavaCC - OriginalChecksum=cb7fb0bfe7a862a49c0012cc66ce167d (do not edit this line) */
