/* Generated By:JJTree: Do not edit this line. varDeclStat_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

import java.util.List;

public
class varDeclStat_AST extends SimpleNode {
  List<Unit> variables;
  public varDeclStat_AST(int id) {
    super(id);
  }

  public varDeclStat_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitVarDeclStat(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data,
		String brkLbl, String contLbl, String nextLbl) {
	codeGenerator.visitVarDecl(this, data, brkLbl, contLbl, nextLbl);
}
}
/* JavaCC - OriginalChecksum=8ec26b5dc58077564d238ade9ecbfd69 (do not edit this line) */
