/* Generated By:JJTree: Do not edit this line. whileStat_AST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stage2;

public
class whileStat_AST extends SimpleNode {
  binaryExpression_AST condition;
  SimpleNode body;
  public whileStat_AST(int id) {
    super(id);
  }

  public whileStat_AST(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, ScopeElement data) {
    return visitor.visitWhileStat(this, data);
  }

public void cAccept(CodeGenerator codeGenerator, ScopeElement data,
		String brkLbl, String contLbl, String nextLbl) {
	codeGenerator.visitWhileStat(this, data, brkLbl, contLbl, nextLbl);
}
}
/* JavaCC - OriginalChecksum=bde3061e834ce3f3b7adacd770a6fce8 (do not edit this line) */
